### ISSUE TITLE
Provide a comparison to kernelshark

### ISSUE THREAD

**Issue by ampresent** [cunctator/traceshark#1]
These two tools seem alike. What are the pros & cons, or differences in your view ?
Can you kindly provide it in the README, so we can easily know what we can expect ?

**Comment by cunctator** [comment]
I am not interested in providing a comparison between traceshark and kernelshark. I am not an expert on how to use kernelshark. Doing a fair and accurate comparison between the two would be a lot of work for me and I am not convinced that the end result would be accurate and unbiased. I would rather spend this time and effort on improving traceshark and it's documentation.

What I try to do is to provide a few screenshots and a fairly detailed documentation of the functionality in the README.md, "1. Introduction to Traceshark", especially in the subsection "1.1.2 Functionality of the buttons".

**Comment by ampresent** [comment]
Fair point. Better document will do the same. Thank!
