### ISSUE TITLE
Pre-built releases

### ISSUE THREAD

**Issue by ampresent** [cunctator/traceshark#2]
Qt building environment is complex to setup to many of us.
Are you planning on provide pre-built releases in the future.
Thanks!

**Comment by cunctator** [comment]
I do not really want to provide pre-built binaries. I believe that setting up the build environment should be easy enough. On most Linux distros it can be accomplished with a single command.

Of course, if you are using a shared machine without root privileges, then it may indeed be difficult.

For those who do not know how to setup the build environment, I have added a new section  to the documentation  "2.1 How to set up your build environment". I provide examples for Debian, Ubuntu and Fedora. Will this work for you?

There are currently binary packages in Debian and Ubuntu, however they exist only for Ubuntu 20.10 and Debian Bullseye; neither of these two are released at this time.

**Comment by ampresent** [comment]
I don't have a PC linux distribution.
I'm developing remotely on some Linux servers through a macbook PC.
Those servers won't allow me to setup VNC or something like that.
And I believe cross compiling for macOS target will be slightly more complex.

And it's your decision. I'm just giving some advice. :-)

**Comment by ampresent** [comment]
Yes. I tried to install kernelshark on my debian and ubuntu docker container, hoping it would make it easier and failed. Maybe I should try the unstable preview distribution.

**Comment by cunctator** [comment]
Have you considered using virtualbox to run a virtualized Linux on your macbook?
If a traceshark binary existed, how would you use it? Running it inside docker on OS X?
To me it sounds like you would need a OS X port of traceshark.

**Comment by ampresent** [comment]
Yes. An macOS port is great. But I now think it might be too much work for you. So just drop it.
I'll try it with virtualbox. thx!

**Comment by cunctator** [comment]
I don't believe that compiling traceshark for OS X would be very difficult, if one used macports. I am only aware of one Linux specific API being used in traceshark and that is the usage of prctl() in threads/tthread.cpp and that would be easy to get rid of. Probably there are a few other places that would need patching but I would expect the work to be slight.

The biggest problem for me is that I don't have much OS X hardware at the moment, only an almost 10 year old mac mini that I have not switched on for over 5 years. I would probably need to install a new version of OS X and then reinstall macports.

**Comment by cunctator** [comment]
I have now fixed traceshark so that it compiles on macOS. Currently, only the master branch builds on macOS. I added information to the README.md about how to set up the Qt build environment on macOS. It's in section "2.1 How to set up your build environment".
![traceshark-on-macos](https://user-images.githubusercontent.com/4447863/82944006-c5c4a400-9f9a-11ea-9127-5b9e33bbcb9b.png)

**Comment by cunctator** [comment]
I don't have plans to get into the business of distributing binary packages. Currently a few distros are packaging traceshark.

MacOS users are encouraged to try to build a native version with brew and Qt6 as described in the README.
